'use strict';
const assert=require('assert');
const {maskAchievementDefinitions,achievementTrustBoundary}=require('./secret-visibility');
const definition={key:'paper_favorite',title:'Paper Favorite',rarity:'Epic',is_secret:true,client_metadata:{secret:true,rule_hint:'must not leak'}};
const locked=maskAchievementDefinitions([definition],[])[0];
assert.strictEqual(locked.title,'???'); assert.strictEqual(locked.rarity,null); assert.strictEqual(locked.client_metadata.rule_hint,undefined); assert.strictEqual(locked.client_metadata.locked_label,'Hidden Achievement');
assert.strictEqual(locked.key,'visible_secret_slot_1','the semantic key must not reveal the Secret');
const unlocked=maskAchievementDefinitions([definition],[{achievement_key:'paper_favorite'}])[0];
assert.strictEqual(unlocked.title,'Paper Favorite'); assert.strictEqual(unlocked.rarity,'Epic');
const discovery={key:'love_dive',title:'LOVE DIVE',rarity:'Legendary',is_discovery:true,client_metadata:{discovery:true,rule_hint:'never leak'}};
const unknown=achievementTrustBoundary({definitions:[definition,discovery],progress:[{achievement_key:'love_dive',current_value:39}],unlocks:[]});
assert.strictEqual(unknown.definitions.length,1,'locked Discovery has no slot or placeholder');
assert.strictEqual(unknown.availableCount,1,'locked Discovery does not alter the denominator');
assert.strictEqual(unknown.progress.length,0,'Discovery progress never crosses the trust boundary');
assert(!JSON.stringify(unknown).includes('love_dive')&&!JSON.stringify(unknown).includes('LOVE DIVE'),'keys and titles cannot leak');
const revealed=achievementTrustBoundary({definitions:[definition,discovery],progress:[],unlocks:[{achievement_key:'love_dive'}]});
assert.strictEqual(revealed.definitions.length,2); assert.strictEqual(revealed.availableCount,2); assert.strictEqual(revealed.definitions.find(x=>x.is_discovery).title,'LOVE DIVE');
console.log('secret visibility tests passed');
