'use strict';
const assert=require('assert');
const R=require('./temporal-listening-rules');
const base={identity_complete:true,coverage_continuous:true,epoch_id:'e',window_start:'2026-01-01T00:00:00Z',window_end:'2026-01-31T00:00:00Z'};
assert.equal(R.nightShift([{...base,night_scrobbles:44,total_scrobbles:60}]),null);
assert.equal(R.nightShift([{...base,night_scrobbles:45,total_scrobbles:60}]).key,'night_shift');
assert.equal(R.allRoads([{...base,artist_scrobbles:74,total_scrobbles:150}]),null);
assert.equal(R.allRoads([{...base,artist_scrobbles:75,total_scrobbles:150}]).key,'all_roads_lead_to');
assert.equal(R.allRoads([{...base,artist_scrobbles:150,total_scrobbles:150,coverage_continuous:false}]),null);
const decades=Object.fromEntries([1960,1970,1980,1990,2000].map(d=>[d,[`${d}a`,`${d}b`,`${d}c`]]));
assert.equal(R.timeTraveler({...base,decade_tracks:decades}).key,'time_traveler');
assert.equal(R.timeTraveler({...base,decade_tracks:{...decades,2000:['x','y']}}),null);
assert.equal(R.fromDusk({...base,hour_counts:Object.fromEntries(Array.from({length:24},(_,h)=>[h,3]))}).key,'from_dusk_till_dawn');
assert.equal(R.fromDusk({...base,hour_counts:{0:3}}),null);
assert.equal(R.lostAndFound([{...base,same_epoch:true,identity_complete:true,coverage_at_previous:true,coverage_at_return:true,gap_days:364}]),null);
assert.equal(R.lostAndFound([{...base,same_epoch:true,identity_complete:true,coverage_at_previous:true,coverage_at_return:true,gap_days:365}]).key,'lost_and_found');
assert.equal(R.lostAndFound([{...base,same_epoch:true,identity_complete:true,coverage_at_previous:false,coverage_at_return:true,gap_days:500}]),null);
const months=Array.from({length:3},(_,i)=>({id:`m${i}`,period_type:'month',completeness:'complete',coverage_continuous:true,local_start:`2026-0${i+1}-01`,local_end:`2026-0${i+2}-01`,rankings:{release_groups:[{id:'r',rank:5,count:15}]}}));
assert.equal(R.comfortAlbum(months).key,'comfort_album');
assert.equal(R.comfortAlbum(months.slice(0,2)),null);
const weeks=Array.from({length:6},(_,i)=>({id:`w${i}`,period_type:'week',completeness:'complete',coverage_continuous:true,local_start:new Date(Date.UTC(2026,0,5+i*7)).toISOString().slice(0,10),local_end:new Date(Date.UTC(2026,0,12+i*7)).toISOString().slice(0,10),scrobble_total:25,rankings:{artists:[{id:'a',rank:1,count:8}]}}));
assert.equal(R.myWorld(weeks).key,'my_world');
assert.equal(R.myWorld(weeks.map((w,i)=>i===3?{...w,scrobble_total:24}:w)),null);
console.log('temporal-listening-rules.test.js passed');
